# fly.toml app configuration file generated for neonification on 2024-07-29T20:34:56+05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'neonification'
primary_region = 'sin'

[build]

[env]
  PORT = '3000'
  SCOPES = 'read_files,read_publications,write_files,write_products,write_publications'
  SHOPIFY_API_KEY = '09972c7bdbe48588b9917ef3e87b0edb'
  SHOPIFY_APP_URL = 'https://neonification.fly.dev'

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
